### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ilyapasyuk** [maystrova/managment-ui-kit#27]
- [x] Список файлов в задаче 4x (4 в строке) (CSS grid)
- [x] Чекбокс в соответствии с макетом (Google - "styling checkbox css")
- [x] Убрать кнопку "Add file" для неавторизованных
- [x] При коментирование как гость переименовать лэйблы пользователя с `User,User` на `Guest` 
- [x] Дизайн модального окна загрузки сделать симпатифней
- [x] убрать тип из списка файлов
- [x] Favicon и title приложения поменять 
- [x] `Editable field` для заголовка задачи и `description` сделать по ширине контейнера
- [x] Иконку крестика сделать симпатифной иконкой
- [x] На модалке share поменять текст рыбу на, что-то адекватное или удалить.
- [x] в `sidebar` `hover` по спискам должен быть в край блока
- [x] При успешном создании проекта удалять текст из `input`
- [x] Симпатифный лоадинг загрузки списка задач
- [x] `Description` при создании задачи сделать больше в 2 раза
- [x] При редактирование description в задаче кнопки `save`, `cancel` отображать под полем
- [x] При редактирование задачи баг с отображением имени задачи в поле редактирования
- [x] Loader на списке задач показывать поверх списка, чтобы блокировалось взаимодействие со списком задач
- [x] При редактировании description в поле редактирования отображается "тест по умолчанию"
- [x] В некоторых задачах не отображается превью файлов
- [x] Переименовать имена задач для режима демонстрации, сейчас везде "new task" 
- [x] У некоторых задач в списке не отображается имя
- [x] текст `Add a Task` переименовать в `Create task`
- [x] После списка комментариев отображается большое белое поле, оно должно заканчиваться после комментариев

**Comment by ilyapasyuk** [comment]
https://github.com/maystrova/managment-ui-kit/pull/28
